### ISSUE TITLE
Blocks forever if no beacons are present?

### ISSUE THREAD

**Issue by m4444x** [davidgyoung/ble-scanner#3]
Could it be that the read call blocks forever when there are no beacons in range?

**Comment by m4444x** [comment]
I just checked my logs and it appears it was working fine until about a week ago (around the time I did the last apt-get upgrade). Now the program doesn't seem to exit anymore when there are no beacons. Maybe the upgrade changed something in the bluetooth drivers? Or is it just my setup?

![image](https://user-images.githubusercontent.com/121694333/210132866-23d721a5-2eaa-4545-9d94-6799c7db592c.png)

**Comment by davidgyoung** [comment]
Ouch!  Thanks for this report.  I will be careful not to do an apt-get upgrade on any machines where I am using this until I we can isolate the issue and find a solution.

You may wish to try going backward on your installed version of the bluez packages to see if that solves the problem, as this is a likely dependency that could cause this issue.  Here is what I have on a working install:

```
$ apt list --installed | grep bluez

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

bluez-firmware/oldstable,now 1.2-4+rpt8 all [installed,automatic]
bluez/stable,now 5.55-3.1 armhf [installed,automatic]
```

**Comment by m4444x** [comment]
```
bluez-firmware/stable,stable,now 1.2-4+rpt10 all [installed,automatic]
bluez/stable,now 5.55-3.1+rpt2 arm64 [installed]
```
I downgraded the bluez-firmware to "1.2-4" now and indeed the program seems to work as expected again! Sometimes it takes a little longer to finish but not more than a few seconds.

```
bluez-firmware/stable,stable,now 1.2-4 all [installed,upgradable to: 1.2-4+rpt10]
bluez/stable,now 5.55-3.1+rpt2 arm64 [installed]
```

**Comment by m4444x** [comment]
Actually after some time "1.2-4" exhibits the same behaviour for me. It's just not as frequent as in "1.2-4+rpt10", where it seems to do it all the time.
Makes me wonder if this is maybe the intended behaviour now?
Anyway I think I got a solution. See here: #4

**Comment by davidgyoung** [comment]
Thank you, @m4444x
